type CaseFolder {
  id: ID!
  createdAt: String!
  updatedAt: String!
  rule: CaseRule!
  disable: Boolean!
  # reasonCategory: ReasonCategory!
  # reasonDescription: String!
  closed: Boolean!
}

enum CaseRule {
  latestReviewUpdatedAt
}
