type Comment {
  id: ID!
  activityId: String
  author: User @relation(name: "WROTE", direction: "IN")
  content: String!
  contentExcerpt: String
  post: Post @relation(name: "COMMENTS", direction: "OUT")
  createdAt: String
  updatedAt: String
  deleted: Boolean
  disabled: Boolean
  reviewedByModerator: User
    @cypher(
      statement: """
        MATCH (this)<-[:BELONGS_TO]-(claim:Claim)<-[review:REVIEWED]-(moderator:User)
        RETURN moderator
        ORDER BY claim.updatedAt DESC, review.updatedAt DESC
        LIMIT 1
      """
    )
}

type Mutation {
  CreateComment(
    id: ID
    postId: ID!
    content: String!
    contentExcerpt: String
  ): Comment
  UpdateComment(
    id: ID!
    content: String!
    contentExcerpt: String
  ): Comment
  DeleteComment(id: ID!): Comment
}
