type EmailAddress {
  id: ID!
  email: String!
  verifiedAt: String
  createdAt: String
}

type Mutation {
  Signup(email: String!): EmailAddress
  SignupByInvitation(email: String!, token: String!): EmailAddress
  SignupVerification(
    nonce: String!
    name: String!
    email: String!
    password: String!
    slug: String
    avatar: String
    coverImg: String
    avatarUpload: Upload
    locationName: String
    about: String
  ): User
}
