type EMOTED @relation(name: "EMOTED") {
  from: User
  to: Post

  emotion: Emotion
  createdAt: String
  updatedAt: String
}

input _EMOTEDInput {
  emotion: Emotion
  createdAt: String
  updatedAt: String
}

input _PostEMOTEDFilter {
  emotion_in: [Emotion]
  createdAt: String
  updatedAt: String
}

type Mutation {
  AddPostEmotions(to: _PostInput!, data: _EMOTEDInput!): EMOTED
  RemovePostEmotions(to: _PostInput!, data: _EMOTEDInput!): EMOTED
}
