type FILED {
  createdAt: String!
  reasonCategory: ReasonCategory!
  reasonDescription: String!
  submitter: User
}

# this list equals the strings of an array in file "webapp/constants/modals.js"
enum ReasonCategory {
  other
  discrimination_etc
  pornographic_content_links
  glorific_trivia_of_cruel_inhuman_acts
  doxing
  intentional_intimidation_stalking_persecution
  advert_products_services_commercial
  criminal_behavior_violation_german_law
}

type FiledReport {
  createdAt: String!
  reasonCategory: ReasonCategory!
  reasonDescription: String!
  reportId: ID!
  resource: ReportedResource!
}

type Mutation {
  fileReport(resourceId: ID!, reasonCategory: ReasonCategory!, reasonDescription: String!): FiledReport
}