type Image {
  url: ID!,
  # urlW34: String,
  # urlW160: String,
  # urlW320: String,
  # urlW640: String,
  # urlW1024: String,
  alt: String,
  sensitive: Boolean,
  aspectRatio: Float,
}

input ImageInput {
  alt: String,
  upload: Upload,
  sensitive: Boolean,
  aspectRatio: Float,
}
