type InvitationCode {
  id: ID!
  nonce: String
  generatedBy: User @relation(name: "GENERATED", direction: "IN")

  #createdAt: DateTime
  #usedAt: DateTime
  createdAt: String
  usedAt: String
}

type Mutation {
  CreateInvitationCode(id: ID, nonce: String, createdAt: String): InvitationCode
}
