type InvitationCode {
  id: ID!
  token: String
  generatedBy: User @relation(name: "GENERATED", direction: "IN")

  #createdAt: DateTime
  #usedAt: DateTime
  createdAt: String
}

type Mutation {
  CreateInvitationCode: InvitationCode
}
