type Location {
  id: ID!
  name: String!
  nameEN: String
  nameDE: String
  nameFR: String
  nameNL: String
  nameIT: String
  nameES: String
  namePT: String
  namePL: String
  type: String!
  lat: Float
  lng: Float
  parent: Location @cypher(statement: "MATCH (this)-[:IS_IN]->(l:Location) RETURN l")
}