type Notification {
  id: ID!
  read: Boolean
  reason: String
  createdAt: String
  user: User @relation(name: "NOTIFIED", direction: "OUT")
  post: Post @relation(name: "NOTIFIED", direction: "IN")
  comment: Comment @relation(name: "NOTIFIED", direction: "IN")
}
