type NOTIFIED {
	from: NotificationSource
	to: User
	created_at: DateTime
	read: Boolean
	reason: NotificationReason
}

union NotificationSource = Post | Comment

enum NotificationOrdering {
	created_at_asc
	created_at_desc
}

enum NotificationReason {
	mentioned_in_post
	mentioned_in_comment
	commented_on_post
}

type Query {
	notifications(read: Boolean, orderBy: NotificationOrdering): [NOTIFIED]
}

type Mutation {
	markAsRead(id: ID!): NOTIFIED
}