type REVIEWED {
  createdAt: String!
  updatedAt: String!
  # reasonCategory: ReasonCategory
  # reasonDescription: String
  disable: Boolean!
  closed: Boolean!

  reportId: ID!
  reportCreatedAt: String!
  reportUpdatedAt: String!
  reportDisable: Boolean!
  reportClosed: Boolean!
  
  moderator: User
  type: String
  user: User
  post: Post
  comment: Comment
}

type Mutation {
  review(resourceId: ID!, disable: Boolean, closed: Boolean): REVIEWED
}
