type REVIEWED {
  createdAt: String!
  updatedAt: String!
  # reasonCategory: ReasonCategory
  # reasonDescription: String
  disable: Boolean!
  closed: Boolean!

  claimId: ID!
  claimDisable: Boolean!
  claimUpdatedAt: String!
  claimClosed: Boolean!
  
  moderator: User
    # Wolle @cypher(statement: "MATCH (resource)<-[:DECIDED]-(moderator:User) RETURN moderator")
  # not yet supported
  # Wolle resource: ReportResource
  #   @cypher(statement: "MATCH (resource)<-[:DECIDED]-(:User) RETURN resource")
  type: String
    # @cypher(statement: "MATCH (resource)<-[:DECIDED]-(user:User) RETURN labels(resource)[0]")
  user: User
  post: Post
  comment: Comment
}

type Mutation {
  review(resourceId: ID!, disable: Boolean, closed: Boolean): REVIEWED
}
