#!/usr/bin/env bash
set -e
for var in "SSH_USERNAME" "SSH_HOST" "MONGODB_USERNAME" "MONGODB_PASSWORD" "MONGODB_DATABASE" "MONGODB_AUTH_DB"
do
  if [[ -z "${!var}" ]]; then
    echo "${var} is undefined"
    exit 1
  fi
done

/migration/mongo/import.sh
/migration/neo4j/import.sh
